ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS instagram_url TEXT NOT NULL DEFAULT '#',
    ADD COLUMN IF NOT EXISTS youtube_url TEXT NOT NULL DEFAULT '#',
    ADD COLUMN IF NOT EXISTS soundcloud_url TEXT NOT NULL DEFAULT '#',
    ADD COLUMN IF NOT EXISTS radio_url TEXT NOT NULL DEFAULT '#';
